version: '3.8'

volumes:
  rabbitmq_data:
  stripe_cli:

services:
  
  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  ###################################
  # Admin: The Admin microservice
  ###################################
  admin:
    image: admin:0.21
    restart: always
    build: 
      context: ./
      dockerfile: './Docker/Dockerfile.admin'
    ports:
      - "5000:5000"

  # ###################################
  # # Student: The Student microservice
  # ###################################
  student:
    image: student:0.21
    restart: always
    build: 
      context: ./
      dockerfile: './Docker/Dockerfile.student'
    ports:
      - "5005:5005"

  ###################################
  # Tutor: The Tutor microservice
  ###################################
  tutor:
    image: tutor:0.21
    restart: always
    build: 
      context: ./
      dockerfile: './Docker/Dockerfile.tutor'
    ports:
      - "5003:5003"

  # ###################################
  # # classSchedule: The classSchedule microservice
  # ###################################
  classSchedule:
    image: classschedule:0.21
    restart: always
    build: 
      context: ./
      dockerfile: './Docker/Dockerfile.classSchedule'
    ports:
      - "5004:5004"

  # ###################################
  # # registerClass: The registerClass microservice
  # ###################################
  registerClass:
    image: registerclass:0.21
    restart: always
    build: 
      context: ./
      dockerfile: './Docker/Dockerfile.registerClass'
    depends_on:
      - tutor
      - classSchedule
    ports:
      - "5009:5009"
  
  # ###################################
  # # ShowClasses: The ShowClasses microservice
  # ###################################
  showClasses:
    image: showclasses:0.21
    restart: always
    build:
      context: ./
      dockerfile: './Docker/Dockerfile.showClasses'
    depends_on:
      - tutor
      - classSchedule
      - student
    ports:
      - "5008:5008"

  # ###################################
  # # manageClasses: The manageClasses microservice
  # ###################################
  manageClasses:
    image: manageclasses:0.21
    restart: always
    build:
      context: ./
      dockerfile: './Docker/Dockerfile.manageClasses'
    depends_on:
      - admin
      - classSchedule
    ports:
      - "5002:5002"

  # ###################################
  # # paymentSuccess: The paymentSuccess queue receiver microservice
  # ###################################
  paymentsuccess:
    image: paymentsuccess:0.21
    restart: always
    build:
      context: .
      dockerfile: './Docker/Dockerfile.paymentSuccess'
    
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1


  # ###################################
  # # approveTutor: The approveTutor queue receiver microservice
  # ###################################
  approvetutor:
    image: approvetutor:0.21
    restart: always
    build:
      context: .
      dockerfile: './Docker/Dockerfile.approveTutor'
    
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  # ###################################
  # # rejectTutor: The rejectTutor queue receiver microservice
  # ###################################
  rejecttutor: 
    image: rejecttutor:0.21
    restart: always
    build:
      context: .
      dockerfile: './Docker/Dockerfile.rejectTutor'
    
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
  
  # ###################################
  # # Notification: The Notification microservice
  # ###################################
  notification:
    image: notification:0.21
    restart: always
    build:
      context: .
      dockerfile: './Docker/Dockerfile.notification'
  
    depends_on:
      - approvetutor
      - rejecttutor
      - paymentsuccess
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5010:5010"

    


  ###################################
  # manageTutors: The manageTutors microservice
  ###################################
  manageTutors:
    image: managetutors:0.21
    restart: always
    build:
      context: ./
      dockerfile: './Docker/Dockerfile.manageTutors'
    depends_on:
      - admin
      - tutor
      - notification
    ports:
      - "5001:5001"

  
  
  # ###################################
  # # transaction: The transaction microservice
  # ###################################
  transaction:
    image: transaction:0.21
    restart: always
    build:
      context: ./
      dockerfile: './Docker/Dockerfile.transaction'
    ports:
      - "5007:5007"

 # ###################################
  # # bookClass: The bookClass microservice
  # ###################################
  bookClass:
    image: bookclass:0.21
    restart: always
    build:
      context: ./
      dockerfile: './Docker/Dockerfile.bookClass'
    depends_on:
      - transaction
      - classSchedule
      - student
      - notification
    ports:
      - "5006:5006"

  ####################################
  # stripeCLI: The stripe CLI   
  ####################################
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe_cli
    command: listen --api-key sk_test_51KikEDLVS1n78x0iu8FVBGGZVjfpkOuWjHvdmT4Y4R3yNMTrYxjiflKfzPTOuurYYf2zE4JA2LCUka4WGsCxuMBA00VBGA47wB --forward-to bookClass:5006/stripeWebhook
    
