FROM python:3-slim

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR ./Microservices

EXPOSE 5005
CMD [ "python", "./classScheduleMS.py" ]
