FROM python:3-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN python -m pip install --no-cache-dir -r requirements.txt

COPY Microservices/adminMS.py ./

EXPOSE 5008
CMD [ "python", "./adminMS.py" ]
