FROM python:3-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN python -m pip install --no-cache-dir -r requirements.txt

COPY Microservices/classScheduleMS.py ./

EXPOSE 5004
CMD [ "python", "./classScheduleMS.py" ]
