FROM python:3-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install pika

RUN python -m pip install --no-cache-dir -r requirements.txt

COPY ./amqp_setup.py ./mailchimpFunctions.py ./approveTutorQR.py ./ 

CMD [ "python", "./approveTutorQR.py" ]
