FROM python:3-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN python -m pip install --no-cache-dir -r requirements.txt

COPY ./approveTutorQR.py ./amqp_setup.py ./mailchimpFunctions.py ./ 

# 

CMD [ "python", "./approveTutorQR.py" ]
# CMD [ "python", "./approveTutorQR.py" ]
